// frontend/src/pages/CarEditPage.jsx
import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { getCar, updateCar } from '../api/carsApi';
import { getApiError } from '../api/http';
import { Alert } from '../components/Alert';
import { CarForm } from '../components/CarForm';

export function CarEditPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [car, setCar] = useState(null);
  const [loading, setLoading] = useState(false);
  const [loadingCar, setLoadingCar] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    async function loadCar() {
      setLoadingCar(true);
      setError('');
      try {
        setCar(await getCar(id));
      } catch (exception) {
        setError(getApiError(exception));
      } finally {
        setLoadingCar(false);
      }
    }

    loadCar();
  }, [id]);

  async function handleSubmit(payload) {
    setLoading(true);
    setError('');
    try {
      await updateCar(id, payload);
      navigate('/');
    } catch (exception) {
      setError(getApiError(exception));
    } finally {
      setLoading(false);
    }
  }

  return (
    <section className="editor-page">
      <div className="section-heading">
        <div>
          <span className="eyebrow">Edición</span>
          <h2>Editar auto</h2>
        </div>
        <Link to="/" className="button button-ghost">Volver</Link>
      </div>
      <Alert>{error}</Alert>
      {loadingCar ? (
        <div className="loading-panel"><span className="loader" /> Cargando auto</div>
      ) : car ? (
        <CarForm initialValues={car} loading={loading} submitLabel="Guardar cambios" onSubmit={handleSubmit} />
      ) : null}
    </section>
  );
}

// frontend/src/app/pages/car-edit/car-edit-page.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { getApiError } from '../../core/api-error';
import { CarService } from '../../core/car.service';
import { CarRequest, CarResponse } from '../../models/car.models';
import { AlertComponent } from '../../shared/alert/alert.component';
import { CarFormComponent } from '../../shared/car-form/car-form.component';

@Component({
  selector: 'app-car-edit-page',
  standalone: true,
  imports: [RouterLink, AlertComponent, CarFormComponent],
  template: `
    <section class="section-heading">
      <div>
        <span class="eyebrow">Editar registro</span>
        <h2>Editar auto</h2>
      </div>
      <a routerLink="/" class="button button-ghost">Volver</a>
    </section>

    <app-alert [message]="error" />

    @if (initialValues) {
      <app-car-form submitLabel="Guardar cambios" [loading]="loading" [initialValues]="initialValues" (saveCar)="save($event)" />
    } @else if (loading) {
      <div class="loading-panel">
        <span class="loader" aria-hidden="true"></span>
        <strong>Cargando auto...</strong>
      </div>
    }
  `
})
export class CarEditPageComponent implements OnInit {
  private readonly carService = inject(CarService);
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly carId = this.route.snapshot.paramMap.get('id') ?? '';

  loading = false;
  error = '';
  initialValues: CarResponse | null = null;

  ngOnInit(): void {
    this.loadCar();
  }

  save(payload: CarRequest): void {
    this.loading = true;
    this.error = '';

    this.carService
      .updateCar(this.carId, payload)
      .pipe(finalize(() => (this.loading = false)))
      .subscribe({
        next: () => void this.router.navigate(['/']),
        error: (error: unknown) => (this.error = getApiError(error))
      });
  }

  private loadCar(): void {
    this.loading = true;
    this.error = '';

    this.carService
      .getCar(this.carId)
      .pipe(finalize(() => (this.loading = false)))
      .subscribe({
        next: (car) => (this.initialValues = car),
        error: (error: unknown) => (this.error = getApiError(error))
      });
  }
}
