// frontend/src/pages/CarCreatePage.jsx
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { createCar } from '../api/carsApi';
import { getApiError } from '../api/http';
import { Alert } from '../components/Alert';
import { CarForm } from '../components/CarForm';

export function CarCreatePage() {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  async function handleSubmit(payload) {
    setLoading(true);
    setError('');
    try {
      await createCar(payload);
      navigate('/');
    } catch (exception) {
      setError(getApiError(exception));
    } finally {
      setLoading(false);
    }
  }

  return (
    <section className="editor-page">
      <div className="section-heading">
        <div>
          <span className="eyebrow">Nuevo registro</span>
          <h2>Crear auto</h2>
        </div>
        <Link to="/" className="button button-ghost">Volver</Link>
      </div>
      <Alert>{error}</Alert>
      <CarForm loading={loading} submitLabel="Guardar auto" onSubmit={handleSubmit} />
    </section>
  );
}

// frontend/src/app/pages/car-create/car-create-page.component.ts
import { Component, inject } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { getApiError } from '../../core/api-error';
import { CarService } from '../../core/car.service';
import { CarRequest } from '../../models/car.models';
import { AlertComponent } from '../../shared/alert/alert.component';
import { CarFormComponent } from '../../shared/car-form/car-form.component';

@Component({
  selector: 'app-car-create-page',
  standalone: true,
  imports: [RouterLink, AlertComponent, CarFormComponent],
  template: `
    <section class="section-heading">
      <div>
        <span class="eyebrow">Nuevo registro</span>
        <h2>Crear auto</h2>
      </div>
      <a routerLink="/" class="button button-ghost">Volver</a>
    </section>

    <app-alert [message]="error" />
    <app-car-form submitLabel="Crear auto" [loading]="loading" (saveCar)="save($event)" />
  `
})
export class CarCreatePageComponent {
  private readonly carService = inject(CarService);
  private readonly router = inject(Router);

  loading = false;
  error = '';

  save(payload: CarRequest): void {
    this.loading = true;
    this.error = '';

    this.carService
      .createCar(payload)
      .pipe(finalize(() => (this.loading = false)))
      .subscribe({
        next: () => void this.router.navigate(['/']),
        error: (error: unknown) => (this.error = getApiError(error))
      });
  }
}
