// frontend/src/app/pages/login/login-page.component.ts
import { Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { getApiError } from '../../core/api-error';
import { AuthService } from '../../core/auth.service';
import { AlertComponent } from '../../shared/alert/alert.component';
import { IconComponent } from '../../shared/icons/icon.component';

@Component({
  selector: 'app-login-page',
  standalone: true,
  imports: [ReactiveFormsModule, RouterLink, AlertComponent, IconComponent],
  template: `
    <main class="auth-page">
      <section class="auth-panel">
        <a routerLink="/" class="auth-brand">
          <span class="brand-mark"><app-icon name="car" /></span>
          <span>Car Manager</span>
        </a>

        <h1>Iniciar sesion</h1>
        <app-alert [message]="error" />

        <form class="auth-form" [formGroup]="form" (ngSubmit)="submit()">
          <label>
            <span>Email</span>
            <input type="email" formControlName="email" autocomplete="email" required />
          </label>

          <label>
            <span>Contrasena</span>
            <input type="password" formControlName="password" autocomplete="current-password" required />
          </label>

          <button type="submit" class="button button-primary" [disabled]="loading || form.invalid">
            @if (loading) {
              <span class="loader" aria-hidden="true"></span>
            } @else {
              <app-icon name="save" />
            }
            Entrar
          </button>
        </form>

        <p class="auth-switch">
          No tienes cuenta?
          <a routerLink="/register">Registrate</a>
        </p>
      </section>
    </main>
  `
})
export class LoginPageComponent {
  private readonly auth = inject(AuthService);
  private readonly formBuilder = inject(FormBuilder);
  private readonly router = inject(Router);

  loading = false;
  error = '';

  readonly form = this.formBuilder.nonNullable.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required, Validators.minLength(6)]]
  });

  submit(): void {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    this.loading = true;
    this.error = '';

    this.auth
      .login(this.form.getRawValue())
      .pipe(finalize(() => (this.loading = false)))
      .subscribe({
        next: () => void this.router.navigate(['/']),
        error: (error: unknown) => (this.error = getApiError(error))
      });
  }
}

// frontend/src/pages/LoginPage.jsx
import { useState } from 'react';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import { Alert } from '../components/Alert';
import { CarIcon } from '../components/Icons';
import { LoadingButton } from '../components/LoadingButton';
import { getApiError } from '../api/http';
import { useAuth } from '../hooks/useAuth';

export function LoginPage() {
  const navigate = useNavigate();
  const { isAuthenticated, login } = useAuth();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  if (isAuthenticated) {
    return <Navigate to="/" replace />;
  }

  async function handleSubmit(event) {
    event.preventDefault();
    setLoading(true);
    setError('');

    const formData = new FormData(event.currentTarget);
    try {
      await login({
        email: formData.get('email').trim(),
        password: formData.get('password')
      });
      navigate('/');
    } catch (exception) {
      setError(getApiError(exception));
    } finally {
      setLoading(false);
    }
  }

  return (
    <main className="auth-page">
      <section className="auth-panel">
        <div className="auth-brand">
          <span className="brand-mark"><CarIcon /></span>
          <span>Mis autos</span>
        </div>
        <h1>Iniciar sesión</h1>
        <Alert>{error}</Alert>

        <form onSubmit={handleSubmit} className="auth-form">
          <label>
            <span>Email</span>
            <input name="email" type="email" autoComplete="email" required />
          </label>
          <label>
            <span>Contraseña</span>
            <input name="password" type="password" autoComplete="current-password" required />
          </label>
          <LoadingButton loading={loading} type="submit" className="button button-primary">
            Entrar
          </LoadingButton>
        </form>

        <p className="auth-switch">
          ¿No tienes cuenta? <Link to="/register">Crear cuenta</Link>
        </p>
      </section>
    </main>
  );
}
