// frontend/src/components/EmptyState.jsx
import { Link } from 'react-router-dom';
import { CarIcon, PlusIcon } from './Icons';

export function EmptyState() {
  return (
    <section className="empty-state">
      <CarIcon className="empty-icon" />
      <h2>No hay autos registrados</h2>
      <p>Agrega tu primer auto para verlo en el tablero.</p>
      <Link to="/cars/new" className="button button-primary">
        <PlusIcon />
        Nuevo auto
      </Link>
    </section>
  );
}

// frontend/src/app/shared/empty-state/empty-state.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { IconComponent } from '../icons/icon.component';

@Component({
  selector: 'app-empty-state',
  standalone: true,
  imports: [RouterLink, IconComponent],
  template: `
    <section class="empty-state">
      <app-icon name="car" />
      <h2>No hay autos registrados</h2>
      <p>Agrega tu primer auto para verlo en el tablero.</p>
      <a routerLink="/cars/new" class="button button-primary">
        <app-icon name="plus" />
        Nuevo auto
      </a>
    </section>
  `
})
export class EmptyStateComponent {}
